"""sessions

Revision ID: 22c5f76074f1
Revises: 1bb70af4f8de
Create Date: 2013-09-10 11:15:34.751264

"""

# revision identifiers, used by Alembic.
revision = '22c5f76074f1'
down_revision = '1bb70af4f8de'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('sessionid', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('expires', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('sessionid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    ### end Alembic commands ###
